name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  test:

    runs-on: ubuntu-latest
    env:
      node-version: '18.x'

    steps:
    - name: ğŸ” Checkout source code 
    - uses: actions/checkout@v3
    - name: ğŸŸ¢ Use node.js $node-version
    - uses: actions/setup-node@v3
      with:
        node-version: $node-version
        cache: 'npm'
    - name: âš™ï¸ Install dependencies
    - run: npm install
    - name: ğŸš¦ Run lint
    - run: npm run lint
    - name: ğŸ§ª Run tests
    - run: npm test
